name: Create release S3 plugin

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Hash of 'Release version x.y.z' commit"
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java SDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Check commit title and extract version
        run: |
          export commit_title=$(git log --pretty=format:%s -1 ${{ github.event.inputs.commit_hash }})
          echo "Commit title: $commit_title"
          if [[ $commit_title =~ ^Release\ version\ [0-9]*\.[0-9]*\.[0-9]*$ ]]; then
            echo "Valid commit title"
          else
            echo "Invalid commit title"
            exit 1
          fi
          export version=$(echo ${commit_title} | sed s/^Release\ version\ //g)
          echo "Will use version ${version}"
          echo "version=${version}" >> $GITHUB_ENV

      - name: Build S3 plugin
        run: |
          ./gradlew :repository-s3:distTar :repository-s3:distZip

          export s3_tar_file=$(ls ./repository-s3/build/distributions/ | grep tar)
          export s3_zip_file=$(ls ./repository-s3/build/distributions/ | grep zip)

          echo s3_tar_file=${tar_file} >> $GITHUB_ENV
          echo s3_zip_file=${zip_file} >> $GITHUB_ENV

          echo s3_tar_path=`realpath ./repository-s3/build/distributions/${tar_file}` >> $GITHUB_ENV
          echo s3_zip_path=`realpath ./repository-s3/build/distributions/${zip_file}` >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git tag -a "v${{ env.version }}" -m "Release version ${{ env.version }}"
          git push origin "v${{ env.version }}"

      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.version }}"
          release_name: "v${{ env.version }}"
          commitish: ${{ github.event.inputs.commit_hash }}
          body: |
            *Fill in*
          draft: true
          prerelease: false

      - name: Upload S3 tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.s3_tar_path }}
          asset_name: ${{ env.s3_tar_file }}
          asset_content_type: application/tar

      - name: Upload S3 zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.s3_zip_path }}
          asset_name: ${{ env.s3_zip_file }}
          asset_content_type: application/zip
